version: "3.8"
services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
    ports:
      - 127.0.0.1:${DATABASE_LOCAL_PORT}:5432
    restart: always

  app:
    build: .
    restart: always
    volumes:
      - ${PWD}/prod.env:/app/.env
    command: bash ./start_server.sh
    ports:
      - 127.0.0.1:8008:80
    depends_on:
      - db

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    command: "listen --api-key ${STRIPE_SECRET_KEY} --device-name ${STRIPE_DEVICE_NAME} --forward-to web:8000/payment/webhook/"
    environment:
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_DEVICE_NAME: ${STRIPE_DEVICE_NAME}
    depends_on:
      - db
volumes:
  db_data:
