"""empty message

Revision ID: 0b8c87426215
Revises: a23939041c76
Create Date: 2022-10-20 18:28:28.918049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8c87426215'
down_revision = 'a23939041c76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'api_keys', ['id'])
    op.create_unique_constraint(None, 'api_keys_domains', ['id'])
    op.create_unique_constraint(None, 'firmwares', ['id'])
    op.create_unique_constraint(None, 'group_invite_codes', ['id'])
    op.create_unique_constraint(None, 'raw_datas', ['id'])
    op.create_unique_constraint(None, 'sensor_datas', ['id'])
    op.create_unique_constraint(None, 'sensor_groups', ['id'])
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.String(length=128), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    op.drop_constraint(None, 'sensor_groups', type_='unique')
    op.drop_constraint(None, 'sensor_datas', type_='unique')
    op.drop_constraint(None, 'raw_datas', type_='unique')
    op.drop_constraint(None, 'group_invite_codes', type_='unique')
    op.drop_constraint(None, 'firmwares', type_='unique')
    op.drop_constraint(None, 'api_keys_domains', type_='unique')
    op.drop_constraint(None, 'api_keys', type_='unique')
    # ### end Alembic commands ###
