"""empty message

Revision ID: 46fa1f4a3034
Revises: 60098b186c44
Create Date: 2022-10-21 17:49:24.828978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fa1f4a3034'
down_revision = '60098b186c44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
