"""empty message

Revision ID: 60098b186c44
Revises: 0b8c87426215
Create Date: 2022-10-21 14:50:23.384387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60098b186c44'
down_revision = '0b8c87426215'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
